name: Deploy Back End Stage To Heroku

on:
  push:
    branches:
      - CB-31-deploy
    paths:
      - backend/**
      - .github/workflows/stage-backend.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stock-decider-backend-stage" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: "backend"